name: Run tests

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.12]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies from pyproject.toml
        run: |
          python -m pip install --upgrade pip
          pip install .[test]

      - name: Run tests with coverage
        run: |
          pytest tests/ --cov=src/ampiimts --cov-report=xml --cov-report=term-missing --cov-branch

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: Guillaumernd/ampiimts
          files: coverage.xml
